#pragma once
#include <stddef.h>
#include <stdint.h>

// -----------------------------------------------------------------------------
// This file was generated by umsg-gen.
// Source: messages.umsg
//
// DO NOT EDIT THIS FILE DIRECTLY.
// Edit the corresponding .umsg schema and re-run umsg-gen instead.
// -----------------------------------------------------------------------------

#include <umsg/marshalling.hpp>

struct Heartbeat
{
    uint32_t uptime_ms;

    static const uint32_t kMsgHash = 0xF5BA0031u;
    static const size_t kPayloadSize = sizeof(uint32_t);

    bool encode(umsg::bufferSpan& payload) const
    {
        if (!payload.data) return false;
        const size_t cap = payload.length;
        umsg::Writer w(payload);
        if (!w.write(uptime_ms)) return false;
        if (w.bytesWritten() > cap) return false;
        payload.length = w.bytesWritten();
        return true;
    }

    bool decode(umsg::bufferSpan payload)
    {
        if (payload.length < kPayloadSize) return false;
        umsg::Reader r(payload);
        if (!r.read(uptime_ms)) return false;
        return true;
    }
};
