#pragma once
#include <stddef.h>
#include <stdint.h>

// -----------------------------------------------------------------------------
// This file was generated by umsg-gen.
// Source: RobotState.umsg
//
// DO NOT EDIT THIS FILE DIRECTLY.
// Edit the corresponding .umsg schema and re-run umsg-gen instead.
// -----------------------------------------------------------------------------

#include <umsg/marshalling.hpp>

struct RobotState
{
    uint8_t mode;
    float battery_voltage;

    static const uint32_t kMsgHash = 0x6F95B45Au;
    static const size_t kPayloadSize = sizeof(uint8_t) + sizeof(float);

    bool encode(umsg::bufferSpan& payload) const
    {
        if (!payload.data) return false;
        const size_t cap = payload.length;
        umsg::Writer w(payload);
        if (!w.write(mode)) return false;
        if (!w.write(battery_voltage)) return false;
        if (w.bytesWritten() > cap) return false;
        payload.length = w.bytesWritten();
        return true;
    }

    bool decode(umsg::bufferSpan payload)
    {
        if (payload.length < kPayloadSize) return false;
        umsg::Reader r(payload);
        if (!r.read(mode)) return false;
        if (!r.read(battery_voltage)) return false;
        return true;
    }
};
