#pragma once
#include <stddef.h>
#include <stdint.h>

// -----------------------------------------------------------------------------
// This file was generated by umsg-gen.
// Source: SensorReading.umsg
//
// DO NOT EDIT THIS FILE DIRECTLY.
// Edit the corresponding .umsg schema and re-run umsg-gen instead.
// -----------------------------------------------------------------------------

#include <umsg/marshalling.hpp>

struct SensorReading
{
    uint32_t sensor_id;
    float value;

    static const uint32_t kMsgHash = 0x4DF97BD2u;
    static const size_t kPayloadSize = sizeof(uint32_t) + sizeof(float);

    bool encode(umsg::bufferSpan& payload) const
    {
        if (!payload.data) return false;
        const size_t cap = payload.length;
        umsg::Writer w(payload);
        if (!w.write(sensor_id)) return false;
        if (!w.write(value)) return false;
        if (w.bytesWritten() > cap) return false;
        payload.length = w.bytesWritten();
        return true;
    }

    bool decode(umsg::bufferSpan payload)
    {
        if (payload.length < kPayloadSize) return false;
        umsg::Reader r(payload);
        if (!r.read(sensor_id)) return false;
        if (!r.read(value)) return false;
        return true;
    }
};
