#pragma once
#include <stddef.h>
#include <stdint.h>

// -----------------------------------------------------------------------------
// This file was generated by umsg-gen.
// Source: SetLed.umsg
//
// DO NOT EDIT THIS FILE DIRECTLY.
// Edit the corresponding .umsg schema and re-run umsg-gen instead.
// -----------------------------------------------------------------------------

#include <umsg/marshalling.hpp>

struct SetLed
{
    bool state;

    static const uint32_t kMsgHash = 0x18E29F44u;
    static const size_t kPayloadSize = sizeof(bool);

    bool encode(umsg::bufferSpan& payload) const
    {
        if (!payload.data) return false;
        const size_t cap = payload.length;
        umsg::Writer w(payload);
        if (!w.write(state)) return false;
        if (w.bytesWritten() > cap) return false;
        payload.length = w.bytesWritten();
        return true;
    }

    bool decode(umsg::bufferSpan payload)
    {
        if (payload.length < kPayloadSize) return false;
        umsg::Reader r(payload);
        if (!r.read(state)) return false;
        return true;
    }
};
