/*
 * BasicNode.ino
 *
 * Demonstrates a simple umsg Node on Arduino (with a Serial transport).
 *
 * Features:
 * - Subscribes to 'SetLed' (msg_id 4) to toggle LED_BUILTIN.
 * - Publishes 'Heartbeat' (msg_id 1) every 1 second.
 *
 * --- Generating Code ---
 * This example uses code generated by umsg_gen. To regenerate:
 *
 *   python3 ../../tools/umsg_gen/umsg_gen.py messages.umsg -o .
 *   python3 ../../tools/umsg_gen/umsg_gen.py SetLed.umsg -o .
 *
 * This produces:
 *   messages/Heartbeat.hpp
 *   messages/SetLed.hpp
 */

#include <umsg/transports/arduino.hpp>
#include <umsg/umsg.h>

// Generated headers
#include "messages/Heartbeat.hpp"
#include "messages/SetLed.hpp"

// --- 1. Define Message IDs ---
static const uint32_t MSG_HEARTBEAT_ID = 1;
static const uint32_t MSG_SET_LED_ID = 4;

// --- 2. Hardware / Led Controller ---
// Since registerHandler requires a member function, we group logic here.
struct Controller
{
    void setup()
    {
        pinMode(LED_BUILTIN, OUTPUT);
    }

    umsg::Error onSetLed(const messages::SetLed &msg)
    {
        // 1. Schema Hash checked automatically by Node/Router
        // 2. Decode performed automatically by Node/Router

        // 3. Act
        digitalWrite(LED_BUILTIN, msg.state ? HIGH : LOW);
        return umsg::Error::OK;
    }
};

// --- 3. Globals ---
umsg::ArduinoStream transport(Serial);
umsg::Node<umsg::ArduinoStream, 64, 4> node(transport);
Controller controller;

// --- 4. Setup ---
void setup()
{
    Serial.begin(115200);
    while (!Serial)
        ;

    controller.setup();

    if (!node.ok())
    {
        Serial.println("Node init failed!");
        while (1)
            ;
    }

    // Register Handler: bind ID 4 -> Controller::onSetLed
    if (node.registerHandler(MSG_SET_LED_ID, &controller, &Controller::onSetLed) != umsg::Error::OK)
    {
        Serial.println("Handler registration failed");
    }
}

// --- 5. Loop ---
void loop()
{
    // RX: Drain serial buffer and process frames
    node.poll();

    // TX: Send Heartbeat every 1s
    static unsigned long lastTime = 0;
    if (millis() - lastTime > 1000)
    {
        lastTime = millis();

        messages::Heartbeat hb;
        hb.uptime_ms = millis();

        node.publish(MSG_HEARTBEAT_ID, hb);
    }
}
